---
adminapi_policy_qubes_kernel_release_map:
  fc37: "4.2"
  fc41: "4.3"
adminapi_policy_default_kernel: "{{ lookup('bcduggan.qubes.qubes_prefs', 'default_kernel') }}"
adminapi_policy_default_kernel_prerelease: "{{ adminapi_policy_default_kernel.split('-')[1] }}"
adminapi_policy_default_kernel_distribution: "{{ adminapi_policy_default_kernel_prerelease.split('.')[1] }}"
adminapi_policy_qubes_release: "{{ adminapi_policy_qubes_kernel_release_map[adminapi_policy_default_kernel_distribution] }}"
adminapi_policy_vmrootshell_release_args_map:
  "4.2":
    user: root
  "4.3":
